name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: pro
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
